///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: src/sfx/booty_menu.aks
/// Generation time: Sun Oct 22 17:53:53 CEST 2023
///

/// Song 'g_mysong' metadata macros
#define g_mysong_address  0x42A0
#define g_mysong_size     736
#define g_mysong_end      0x457f

/// Song 'g_mysong' array declaration
extern void g_mysong[g_mysong_size];
