///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: src/sfx/booty_gameover.aks
/// Generation time: Sun Oct 22 17:56:10 CEST 2023
///

/// Song 'g_mysong2' metadata macros
#define g_mysong2_address  0x42A0
#define g_mysong2_size     309
#define g_mysong2_end      0x43d4

/// Song 'g_mysong2' array declaration
extern void g_mysong2[g_mysong2_size];
