///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: assets/fx.aks
/// Generation time: Fri Oct 27 18:11:57 CEST 2023
///

/// Song 'fx' metadata macros
#define fx_address  0x8AB
#define fx_size     250
#define fx_end      0x9a4

/// Song 'fx' array declaration
extern void fx[fx_size];
