///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: assets/fx.aks
/// Generation time: sáb 11 nov 2023 16:53:02 CET
///

/// Song 'fx' metadata macros
#define fx_address  0xE1F
#define fx_size     283
#define fx_end      0xf39

/// Song 'fx' array declaration
extern void fx[fx_size];
