///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: assets/fx.aks
/// Generation time: Sun Oct 29 19:14:00 CET 2023
///

/// Song 'fx' metadata macros
#define fx_address  0xBA7
#define fx_size     283
#define fx_end      0xcc1

/// Song 'fx' array declaration
extern void fx[fx_size];
