///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: assets/gameover.aks
/// Generation time: Fri Oct 27 18:12:05 CEST 2023
///

/// Song 'gameover' metadata macros
#define gameover_address  0x200
#define gameover_size     309
#define gameover_end      0x334

/// Song 'gameover' array declaration
extern void gameover[gameover_size];
