///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: assets/gameover.aks
/// Generation time: lun 23 oct 2023 21:21:07 CEST
///

/// Song 'gameover' metadata macros
#define gameover_address  0x201
#define gameover_size     309
#define gameover_end      0x335

/// Song 'gameover' array declaration
extern void gameover[gameover_size];
