///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: assets/ingame1.aks
/// Generation time: lun 23 oct 2023 15:32:22 CEST
///

/// Song 'g_ingame1' metadata macros
#define g_ingame1_address  0x42A0
#define g_ingame1_size     656
#define g_ingame1_end      0x452f

/// Song 'g_ingame1' array declaration
extern void g_ingame1[g_ingame1_size];
