///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: assets/ingame2.aks
/// Generation time: dom 29 oct 2023 15:52:54 CET
///

/// Song 'ingame2' metadata macros
#define ingame2_address  0x8A9
#define ingame2_size     767
#define ingame2_end      0xba7

/// Song 'ingame2' array declaration
extern void ingame2[ingame2_size];
