///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: assets/ingame1.aks
/// Generation time: Thu Oct 26 10:59:20 CEST 2023
///

/// Song 'ingame1' metadata macros
#define ingame1_address  0x61B
#define ingame1_size     656
#define ingame1_end      0x8aa

/// Song 'ingame1' array declaration
extern void ingame1[ingame1_size];
