///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: assets/ingame3.aks
/// Generation time: Tue Nov 28 22:46:18 CET 2023
///

/// Song 'ingame3' metadata macros
#define ingame3_address  0xBA8
#define ingame3_size     631
#define ingame3_end      0xe1e

/// Song 'ingame3' array declaration
extern void ingame3[ingame3_size];
