///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: assets/ingame1.aks
/// Generation time: mar 24 oct 2023 21:38:01 CEST
///

/// Song 'ingame1' metadata macros
#define ingame1_address  0x61C
#define ingame1_size     656
#define ingame1_end      0x8ab

/// Song 'ingame1' array declaration
extern void ingame1[ingame1_size];
