///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: assets/menu.aks
/// Generation time: jue 26 oct 2023 08:02:15 CEST
///

/// Song 'menu' metadata macros
#define menu_address  0x337
#define menu_size     740
#define menu_end      0x61a

/// Song 'menu' array declaration
extern void menu[menu_size];
