///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: assets/menu.aks
/// Generation time: Sun Nov  5 19:48:32 CET 2023
///

/// Song 'menu' metadata macros
#define menu_address  0x335
#define menu_size     740
#define menu_end      0x618

/// Song 'menu' array declaration
extern void menu[menu_size];
