///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: assets/menu.aks
/// Generation time: lun 23 oct 2023 15:32:26 CEST
///

/// Song 'g_menu' metadata macros
#define g_menu_address  0x42A0
#define g_menu_size     740
#define g_menu_end      0x4583

/// Song 'g_menu' array declaration
extern void g_menu[g_menu_size];
